# Generated by Django 4.0.4 on 2022-07-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('name', models.CharField(max_length=127, verbose_name='상품 이름')),
                ('description', models.TextField(blank=True, default='', verbose_name='상품 설명')),
                ('target_fund', models.PositiveIntegerField(default=0, verbose_name='목표 금액')),
                ('fund_per_once', models.PositiveIntegerField(default=0, verbose_name='1회 펀딩 금액')),
                ('total_fund', models.PositiveIntegerField(default=0, verbose_name='총 펀딩 금액')),
                ('end_date', models.DateTimeField(verbose_name='펀딩 종료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게시자')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='펀딩 상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='펀딩자')),
            ],
            options={
                'db_table': 'funding',
            },
        ),
    ]
