# Generated by Django 4.0.4 on 2022-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_fund',
            field=models.PositiveIntegerField(verbose_name='목표 금액'),
        ),
    ]
